# Generated by Django 2.1 on 2021-12-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Props',
            new_name='Prop',
        ),
    ]
