# Generated by Django 2.1.5 on 2021-12-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('props', '0002_auto_20211230_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Taste',
        ),
        migrations.RenameField(
            model_name='prop',
            old_name='genre',
            new_name='taste',
        ),
    ]
